### ISSUE TITLE
AWS creds

### ISSUE THREAD

**Issue by daroczig** [nfultz/aws_batch#2]
Can we use `DefaultAWSCredentialsProviderChain` instead of `BasicAWSCredentials` so that we can rely on IAM task roles?

**Comment by nfultz** [comment]
Not really sure what you are talking about, but I think I found some code in the AWS lambda plugin that I can borrow.

**Comment by daroczig** [comment]
After digging in the sources, I see there's a section in the UI to configure the AWS creds as

![image](https://user-images.githubusercontent.com/495736/27014046-c0e6a242-4ef0-11e7-90c9-d6300875b171.png)

So there's no urgent need for an update. But `DefaultAWSCredentialsProviderChain` would still work a lot better so that we do not have to provide/store these as plaintext, but Java SDK could pick up from env vars or IAM Task roles etc as per https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by nfultz** [comment]
Implemented in 69f9179a662e34105db317661e4b590fc43476c2

Also the checkbox to toggle showing those text boxes was surprisingly hard to get right; jelly is mildly awful.

**Comment by nfultz** [comment]
Now that I think about it, I don't like the text boxes anyway and will probably just get rid of them and rely on the default.
