### ISSUE TITLE
Jenkins config page returns "net.sf.json.JSONException: JSONObject["logPollingFreq"] is not a number." if log polling frequency is empty

### ISSUE THREAD

**Issue by neilcar** [nfultz/aws_batch#4]
Description:

If you enable the aws-batch plugin and navigate to the Manage Jenkins/Configure System page, the default value for the "Polling frequency for job status" is blank.  If you submit the page without entering a valid int value, Jenkins returns:

> A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.
> 
> Stack trace
> net.sf.json.JSONException: JSONObject["logPollingFreq"] is not a number.
> 	at net.sf.json.JSONObject.getDouble(JSONObject.java:1948)
> 	at net.sf.json.JSONObject.getInt(JSONObject.java:1967)
> 	at njnm.plugins.aws_batch.AwsBatchBuilder$DescriptorImpl.configure(AwsBatchBuilder.java:296)
> ...

Cause:

configure() checks that the logPollingFreq value exists but doesn't check that it's a valid int.

**Comment by daroczig** [comment]
I can confirm that this is an annoying issue :) Thanks @neilcar  -- @nfultz, can you please / merge / push an updated version of this plugin to the central repo?

**Comment by nfultz** [comment]
This LGTM and I would like to merge it in. Can you point your PR at https://github.com/jenkinsci/aws-batch-plugin instead? This is a legacy repo.

**Comment by nfultz** [comment]
Merged in and pushed to the jenkins repo. thanks for the contribution! :+1:
